package ink_test_runner_odin

// Port of .NET Framework's System.Random (Knuth subtractive). Reproduces
// `new Random(seed).Next()` byte-for-byte so logs generated by this tool
// align with the dotnet test runner's seeded logs.
//
// Reference: https://referencesource.microsoft.com/#mscorlib/system/random.cs

NET_RANDOM_MBIG  :: 0x7FFFFFFF // int.MaxValue
NET_RANDOM_MSEED :: 161803398

Net_Random :: struct {
	inext:      int,
	inextp:     int,
	seed_array: [56]int,
}

net_random_init :: proc(r: ^Net_Random, seed: int) {
	subtraction := seed == min(int) ? max(int) : abs(seed)
	mj := NET_RANDOM_MSEED - subtraction
	r.seed_array[55] = mj
	mk := 1

	for i in 1 ..< 55 {
		ii := (21 * i) % 55
		r.seed_array[ii] = mk
		mk = mj - mk
		if mk < 0 do mk += NET_RANDOM_MBIG
		mj = r.seed_array[ii]
	}

	for _ in 1 ..< 5 {
		for i in 1 ..< 56 {
			r.seed_array[i] -= r.seed_array[1 + (i + 30) % 55]
			if r.seed_array[i] < 0 do r.seed_array[i] += NET_RANDOM_MBIG
		}
	}

	r.inext = 0
	r.inextp = 21
}

net_random_next :: proc(r: ^Net_Random) -> int {
	loc_inext := r.inext + 1
	if loc_inext >= 56 do loc_inext = 1
	loc_inextp := r.inextp + 1
	if loc_inextp >= 56 do loc_inextp = 1

	ret := r.seed_array[loc_inext] - r.seed_array[loc_inextp]
	if ret == NET_RANDOM_MBIG do ret -= 1
	if ret < 0 do ret += NET_RANDOM_MBIG

	r.seed_array[loc_inext] = ret
	r.inext = loc_inext
	r.inextp = loc_inextp
	return ret
}
